# Generated by Django 5.2.7 on 2025-10-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='friends_fri_receive_79aa1f_idx',
            old_name='friends_fri_receive_2db123_idx',
        ),
    ]
