# Generated by Django 5.2.7 on 2025-10-17 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='friendship_order',
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('user__lt', models.F('friend')), ('user__isnull', True), ('friend__isnull', True), _connector='OR'), name='friendship_order'),
        ),
    ]
