# Generated by Django 5.2.7 on 2025-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Запрос в друзья'), ('friend_accept', 'Принятие дружбы'), ('like', 'Лайк'), ('comment', 'Комментарий'), ('follow', 'Подписка'), ('message', 'Новое сообщение')], max_length=30),
        ),
    ]
